In [25]:
import sqlite3
import pandas as pd

In [26]:
# Create in-memory database
conn = sqlite3.connect(':memory:')

# Create cursor object
cursor = conn.cursor()

print("Database created successfully!")

Database created successfully!

In [27]:
cursor.execute("""
CREATE TABLE students (
    student_id INTEGER,
    name TEXT,
    age INTEGER,
    course TEXT,
    marks REAL
)
""")

print("Table 'students' created!")

Table 'students' created!

In [28]:
students_data = [
    (1, 'hardik', 21, 'AI', 85.5),
    (2, 'shree', 22, 'DS', 78.0),
    (3, 'bhagyesh', 20, 'AI', 92.3),
    (4, 'rohan', 21, 'ML', 88.8),
    (5, 'Karan', 23, 'DS', 67.5)
]

cursor.executemany(
    "INSERT INTO students VALUES (?, ?, ?, ?, ?)",
    students_data
)

conn.commit()

print("Data inserted successfully!")

Data inserted successfully!

In [29]:
df = pd.read_sql_query(
    "SELECT * FROM students",
    conn
)

df

   student_id      name  age course  marks
0           1    hardik   21     AI   85.5
1           2     shree   22     DS   78.0
2           3  bhagyesh   20     AI   92.3
3           4     rohan   21     ML   88.8
4           5     Karan   23     DS   67.5

In [30]:
df = pd.read_sql_query(
    "SELECT name, course FROM students",
    conn
)

df

       name course
0    hardik     AI
1     shree     DS
2  bhagyesh     AI
3     rohan     ML
4     Karan     DS

In [31]:
df = pd.read_sql_query(
    "SELECT * FROM students WHERE marks > 80",
    conn
)

df

   student_id      name  age course  marks
0           1    hardik   21     AI   85.5
1           3  bhagyesh   20     AI   92.3
2           4     rohan   21     ML   88.8

In [32]:
df = pd.read_sql_query(
    "SELECT AVG(marks) AS average_marks FROM students",
    conn
)

df

   average_marks
0          82.42

In [33]:
cursor.execute("""
UPDATE students
SET marks = 70
WHERE student_id = 5
""")

conn.commit()

df = pd.read_sql_query(
    "SELECT * FROM students",
    conn
)

df

   student_id      name  age course  marks
0           1    hardik   21     AI   85.5
1           2     shree   22     DS   78.0
2           3  bhagyesh   20     AI   92.3
3           4     rohan   21     ML   88.8
4           5     Karan   23     DS   70.0

In [34]:
cursor.execute(
    "DELETE FROM students WHERE student_id = 2"
)

conn.commit()

df = pd.read_sql_query(
    "SELECT * FROM students",
    conn
)

df

   student_id      name  age course  marks
0           1    hardik   21     AI   85.5
1           3  bhagyesh   20     AI   92.3
2           4     rohan   21     ML   88.8
3           5     Karan   23     DS   70.0

In [35]:
cursor.execute("DROP TABLE students")

print("Table dropped successfully!")

Table dropped successfully!

In [36]:
conn.close()

print("Connection closed!")

Connection closed!